### PR TITLE
Update LibCImGui and bump version

### PR DESCRIPTION
**Pull request by Gnimuc**
x-ref: https://github.com/Gnimuc/CImGui.jl/issues/88

### CODE REVIEW

**Comment by IanButterworth** [comment]
bump

**Comment by Gnimuc** [comment]
cc @jpsamaroo

**Comment by JamesWrigley** [comment]
Does this already work with the 1.89.4 changes? If so, maybe the compat bound should be set to `1` or something.

**Comment by Gnimuc** [comment]
I don't think so.

**Comment by jpsamaroo** [comment]
Sorry for the delay! I'll get this tested this weekend and merged if all works.

**Comment by jpsamaroo** [comment]
Thanks!

**Pull request merged**
